In [1]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x,y = make_classification(n_samples=500,n_features=5,class_sep=3,shuffle=True)

In [3]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=7)

In [4]:
model = LogisticRegression()
model.fit(x_test,y_test)
pred=model.predict(x_test)

In [5]:
model.coef_,model.intercept_

(array([[ 0.97904395,  1.40210911,  0.12333807,  0.41633558, -0.14295473]]),
 array([0.32005977]))

In [6]:
def sigmoid(x):
    return 1/(1+np.exp(x))
def output(x):
    return np.where(x<0.5,0,1)

In [46]:
class logistic:
    def __init__(self,lr=0.1,epochs=100):
        self.coef=None
        self.intercept=None
        self.lr=lr
        self.epoch=epochs
    def fit(self,x_train,y_train):
        self.intercept=0
        x_train=np.insert(x_train,0,1,axis=1)
        self.coef=np.ones(x_train.shape[1])
        for i in range(self.epoch):
            y_hat=sigmoid(np.dot(x_train,self.coef))
            slope = np.dot((y_train-y_hat),x_train)/x_train.shape[0]
            self.coef = self.coef - (self.lr*slope)
        self.intercept=self.coef[0]
        self.coef = self.coef[1:]

    def predict(self,x_test):
        return output(sigmoid(np.dot(x_test,self.coef)))

In [47]:
mera=logistic()
mera.fit(x_train,y_train)
mera_pred=mera.predict(x_test)

In [48]:
x_test.shape,mera_pred.shape

((150, 5), (150,))

In [49]:
mera.coef,mera.intercept

(array([-0.51304382, -1.37771605,  1.19701967,  0.7618853 ,  0.70020419]),
 0.6267632733938662)

In [50]:
mera_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0])

In [51]:
print(accuracy_score(y_test,pred)),print(accuracy_score(y_test,mera_pred))

0.9933333333333333
0.9866666666666667


(None, None)

In [52]:
print(confusion_matrix(y_test,pred))

[[70  0]
 [ 1 79]]


In [53]:
print(confusion_matrix(y_test,mera_pred))

[[70  0]
 [ 2 78]]
